# Generated by Django 2.0.5 on 2018-07-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180705_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='annoucemnet',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
