# Generated by Django 2.0.7 on 2018-07-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(max_length=500, verbose_name='Resposta'),
        ),
    ]
