# Generated by Django 3.1.6 on 2021-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180718_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='correct',
            field=models.BooleanField(blank=True, default=False, verbose_name='Correta?'),
        ),
    ]
