# Generated by Django 3.1.6 on 2021-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Confirmado?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Está ativo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, verbose_name='É da equipe?'),
        ),
    ]
